language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script:
    - cp gradle.properties.example gradle.properties
    - ./gradlew clean assembleDebug testDebug

// From Travis support: "NB: please note that `tools` is listed twice. My understanding is that the first
// `tools` gets an xml containing a repository address, the second uses this repo to install the newer components."